; ModularSensors PlatformIO Project Configuration File
; The 'default_envs' src/ms_cfg for specific peripherals
; http://docs.platformio.org/page/projectconf.html

[platformio]
description = neilh10/ModularSensors/examples/samd_log_display_mmw
default_envs =seeed_wio_terminal
;default_envs = adafruit_express_M4_eink29
;default_envs = adafruit_pygamer

[common]
;cmn_f_cpu=120000000L ;Default
cmn_f_cpu =  48000000L  ;With USB & Also without USBs
;cmn_f_cpu = 12000000L ; fails on Tty
;cmn_f_cpu =  8000000L ;fails on Tty
cmn_lib_deps =
    ; There are 3 levels of code production
    ; The stream ( rel1_dvlp1m) is used in alpha coding and development
    ;  alpha - see a\samd_log_display_mmw - branch (rel1_dvlp1m) allows editing of a\samd_log_display_mmw AND ModularSensors\src and pulls the libs
    ;  development this platformio.ini as (rel1_dvlp1m) editing of examples\samd_log_display_mmw and for build specifies git (rel1_dvlp1m) ModularSensors, and pulls the libs
    ;  production  which forces a full pull of (release1) examples\samd_log_display_mmw and libs, and builds options as needed.
    ;
    ; For alpha coding,
    ; and periodically when need to update all libs including ModularSensors #rel1_dvlp1m
    ; for clean lib - delete .pio,
    ; pio pkg install  - execute
    ; ?? then recomment below - not any more
    ; ?? then WIOT delete .pio/libdeps/xxx/EnviroDIY_modularSensors to not have conflicts with ../../src
    ; 
    ;https://github.com/neilh10/ModularSensors#release1
    https://github.com/neilh10/ModularSensors#rel1_dvlp1m
;  ^^ Use this when you want to pull from a specific branch 
    ; These are latest beyond EnviroDIY releases
    https://github.com/vshymanskyy/StreamDebugger  ;Debug when needed
    ; StreamDebugger ; Same as above
    https://github.com/neilh10/SensorModbusMaster ; default release1
    ;use above https://github.com/enviroDIY/SensorModbusMaster
    https://github.com/neilh10/Adafruit_INA219.git 
    ; del https://github.com/adafruit/SdFat ;- need adafruit/SdFat for multiple SDx
    ;https://github.com/greiman/SdFat.git ;-
    ;https://github.com/neilh10/EnableInterrupt - old v1.0.0 need v1.1
    ;https://github.com/GreyGnome/EnableInterrupt 
    ; del https://github.com/arduino-libraries/NTPClient - repalced
    ;; see lib_samd_deps for   Adafruit_SPIFlash & Adafruit_TinyUSB_Arduino & Adafruit-GFX-Library Adafruit_NeoPixel
    ; Need extra libs, so enable STD_LIBS on 1st pass enable ModularSensors then build pulling in ref libs,
    ;    
; STD_LIBS pulled in by ModularSensors, needed if not enabling ModularSensors to Historical Ref
    ;https://github.com/soligen2010/Adafruit_ADS1X15
    ;https://github.com/adafruit/Adafruit_AM2315
    ;https://github.com/adafruit/Adafruit_AM2320
    ;https://github.com/adafruit/Adafruit_BME280_Library
    ;https://github.com/adafruit/Adafruit_MPL115A2
    ;https://github.com/adafruit/DHT-sensor-library
    ;https://github.com/adafruit/Adafruit_Sensor
    ;https://github.com/milesburton/Arduino-Temperature-Control-Library ;Pulls in DallasTemperature
    ;https://github.com/neilh10/KellerModbus 
    ;https://github.com/EnviroDIY/KellerModbus
    ;https://github.com/NorthernWidget/MS5803
    ;https://github.com/PaulStoffregen/OneWire
    ;https://github.com/knolleary/pubsubclient.git
    ;bug https://github.com/EnviroDIY/TinyGSM.git ; bug EnviroDIY/ModularSensors/issues 311
    https://github.com/neilh10/TinyGSM.git#rel1 ;Bug fixes over Envirodiy 
    https://github.com/EnviroDIY/YosemitechModbus
    https://github.com/neilh10/Arduino-SDI-12#release1
    ;https://github.com/EnviroDIY/Arduino-SDI-12.git bug with extraWakeTime=10
    ;https://github.com/EnviroDIY/Tally_Library.git#Dev_I2C
    ;
    ;Historical reference 
    ;https://github.com/greiman/SdFat.git ;- need adafruit/SdFat for multiple SDx
    ;https://github.com/neilh10/Arduino-SerialCommand 
    https://github.com/neilh10/InsituModbus
    https://github.com/neilh10/KellerModbus
    martinl1/BMP388_DEV@^1.0.11 ; dissapeared from github.com/MartinL1/BMP388_DEV.git
    https://github.com/sparkfun/SparkFun_BQ27441_Arduino_Library

; Ignore these folders or PlatformIO will double count all the dependencies
; Development: ModularSensors Release1: src ?
; ?? .pioenvs, .piolibdeps, .vscode, include, doc, examples, sensor_tests, compile_tests, pioScripts
cmn_lib_ignore = .git, doc, examples, arduino_update, sensor_tests, 
    ;EnviroDIY_ModularSensors
    EnviroDIY_DS3231
    SensorModbusMaster
    Arduino-SDI-12
    TinyGSM
    Adafruit_INA21

lib_deps_avr = ;Specific Mayfly board goes in [Mayfly]

lib_samd_deps =
    ;https://github.com/adafruit/SdFat
    ;https://github.com/adafruit/Adafruit_SPIFlash  ;~ for wio_terminal need Seed
    https://github.com/adafruit/Adafruit_TinyUSB_Arduino.git#0.8.0 ;Has MIDI after 0.8.0. Requires -DUSE_TINYUSB
    ;https://github.com/adafruit/Adafruit_TinyUSB_Arduino ;Has MIDI post 0.8.0. Requires -DUSE_TINYUSB
    ; custom board https://github.com/neilh10/arduino-mcp23017
    ;https://github.com/neilh10/RTCZero ;- conflict with Seeed_Arduino_RTC\RTC_SAMD51.h ;release1 set as default - see lib\RTCsamdLooUQ
    ; ;except when exists kn_depth\lib\RTClib, delete .pio\libdeps\xx\RTClib
    ;https://github.com/neilh10/RTClib
    ;https://github.com/adafruit/Adafruit-GFX-Library
    ;https://github.com/adafruit/Adafruit_EPD
    ;FUT https://github.com/adafruit/Adafruit_NeoPixel
    ; Can be used on any board except Mayfly1.1 as has similar SHT4x
    https://github.com/adafruit/Adafruit_SHT31

lib_featherExpress_deps =
    https://github.com/adafruit/Adafruit_NeoPixel
    #feather_Mx_express means local flash disk (2Mbyte+) & NeoPixel

lib_wio_terminal_deps =
    ; wio terminal getting new WiFi lib
    ;https://github.com/Seeed-Studio/Seeed_Arduino_atWiFi
    ;https://github.com/Seeed-Studio/Seeed_Arduino_FreeRTOS
    ;https://github.com/Seeed-Studio/Seeed_Arduino_atUnified
    ;https://github.com/Seeed-Studio/esp-at-lib
    ; objective figure out why Seeed_Arduino_RTC is needed and not RTCzero
    https://github.com/neilh10/Seeed_Arduino_RTC
    https://github.com/milesburton/Arduino-Temperature-Control-Library
    https://github.com/Seeed-Studio/Seeed_Arduino_rpcWiFi
    https://github.com/Seeed-Studio/Seeed_Arduino_rpcUnified
    https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls
    https://github.com/Seeed-Studio/Seeed_Arduino_FS
    https://github.com/Seeed-Studio/Seeed_Arduino_SFUD

lib_samd21_deps =    

lib_samd51_deps =
    https://github.com/neilh10/EnableInterrupt   ;release1 set as default
    https://github.com/neilh10/Arduino-SDI-12 ;release1 set as default
    ;https://github.com/adafruit/Adafruit_SPIFlash

; for development, can edit directly in these directories ... relative to src_dir
;  Use the src filter to ensure subfolders are built
; If enabled, disable in cmn_lib_deps=[]ModularSensors, and may need to delete duplicate directory .libdeps/ModularSensors
cmn_src_filter = +<*> -<.git/> -<.svn/> ;+<../../../src>  +<../../../src/sensors> +<../../../src/publishers> +<../../../src/modems>

#build_flags  -v for detailed cc verbose, single threaded takes a long time
cmn_build_flags =
    -Isrc
    ;-I../../src ; .h For easy debug
    ;-I../../src/sensors ; .h For easy debug
    !python git_rev_macro.py  ;returns -DPIO_SRC_REV=<git_revision>
    ;-DNO_FIRST_SYNC_WITH_NIST
    ;-DNIST_SYNC_HOURLY
    -DMS_LOGGING_TO_MMW_DEBUG
    ;-DMS_TU_XX_DEBUG_DEEP
    ;-DSTREAMDEBUGGER_DBG
    ;-DMS_DUMP_FREE_RAM
    ;-DMS_TTY_USER_INPUT
    ;-DSerialCommand_inFlash ;requires MS_TTY_USER_INPUT
    ;-DMS_TTY_INPUT_COUNT   ;only if no MS_TTY_USER_INPUT
    ;-DSERIALCOMMAND_DEBUG
    -DMS_LOGGERBASE_POSTS
    ;-DMS_LOGGERBASE_SLEEP_DEBUG ;Need or below
    ;-DMS_LOGGERBASE_DEBUG
    ;-DMS_LOGGERMODEM_DEBUG
    ;-DMS_LOGGERMODEM_DEBUG_DEEP
    ;-DMS_SENSORBASE_DEBUG
    ;-DMS_VARIABLEARRAY_DEBUG
    ;-DMS_VARIABLEARRAY_DEBUG_DEEP
    ;-DMS_VARIABLEBASE_DEBUG
    ;-DMS_VARIABLEBASE_DEBUG_DEEP
    ;-DMS_DATAPUBLISHERBASE_DEBUG
    ;-DMS_ENVIRODIYPUBLISHER_DEBUG
    ;-DMS_THINGSPEAKPUBLISHER_DEBUG
    ;-DMS_UBIDOTSPUBLISHER_DEBUG
    ;-DMS_WIOTERMINAL_RPCWIFI_DEBUG
    ; needs implmenting 
    ;-DMS_WIOTERMINAL_RPCWIFI_DEBUG_DEEP
    ;not working-DCORE_DEBUG_LEVEL=5 ; for rpcUnified 
    ;-DMS_DIGIXBEEWIFI_DEBUG
    ;-DMS_DIGIXBEEWIFI_DEBUG_DEEP
    ;-DMS_DIGIXBEECELLULARTRANSPARENT_DEBUG
    ;-DMS_DIGIXBEECELLULARTRANSPARENT_DEBUG_DEEP
    ;-DMS_DIGIXBEE_DEBUG
    ;-DTINY_GSM_DEBUG=Serial
    ;-DTinyGsmClientXbee_DBG=Serial
    -DSDI12_EXTERNAL_PCINT 
    ;-DMS_BATTERYMANAGEMENT_DEBUG
    ;-DMS_PROCSTATS_DEBUG ?
    ;-DMS_MODEM_DEBUG ?
    ;-DMS_PROCESSORSTATS_DEBUG
    ;-DMS_PROCESSORADC_DEBUG
    ;-DMS_MAXIMDS18_DEBUG
    ;-DMS_TIINA219M_DEBUG
    ;-DMS_SENSIRION_SHT3X_DEBUG
    ;-DMS_AOSONGAM2315_DEBUG
    ;-DMS_EXTERNALVOLTAGE_DEBUG
    ;-DMS_EXTERNALVOLTAGE_DEBUG_DEEP
    ;-DMS_KELLERPARENT_DEBUG
    ;-DMS_KELLERPARENT_DEBUG_DEEP has problem
    ;-DMS_MODBUS_DEBUG
    -DSENSORMODBUSMASTER_NO_DBG
    ;-DMS_ANALOGELECCONDUCTIVITY_DEBUG
    ;-DMS_ANALOGELECCONDUCTIVITY_DEBUG_DEEP
    ;-DMS_SDI12SENSORS_DEBUG ;LT500 sometimes responding
    ;-DMS_SDI12SENSORS_DEBUG_DEEP
    ;For -DMS_SDI12 options: NONE or MS_SDI12_SINGLE_LINE_RESPONSE  OR MS_SDI12_NON_CONCURRENT not BOTH
    ;-DMS_SDI12_SINGLE_LINE_RESPONSE
    ;-DMS_SDI12_NON_CONCURRENT
    ;-DENVIRODIY_SDI12_USE_CRC
    ;-DMS_ENVIRODIYPUBLISHER_DEBUG
    ;-DMS_ENVIRODIYPUBLISHER_DEBUG_DEEP
    ;-DSodaq_DS3231_DEBUG
    -DMS_WATCHDOGAVR_DEBUG
    -DMS_WATCHDOGAVR_DEBUG_DEEP

;https://docs.platformio.org/en/latest/projectconf/sections/env/options/advanced/extra_scripts.html#projectconf-extra-scripts
; Errors with two files 
; Transition by adding must_exist=False to SConscript calls.
; Missing SConscript 'build_files_exclude.py post:build_uf2.py'
cmn_arm_extra_scripts = pre:build_files_exclude.py ;post:build_uf2.py 

[env:seeed_wio_terminal]
platform = atmelsam
board = seeed_wio_terminal
framework = arduino
;upload_port = COM13
lib_ldf_mode = deep+
board_build.f_cpu =  ${common.cmn_f_cpu} 

# lib_ignore Std SAMDx AltSoftSerial SoftwareSerial_ExtInts (ignored in SAMD12 Autonomo)
# SensorModbusMaster_ID1824\SensorModbusMaster.cpp.o - M4 Register errors, error: 'REG_GCLK_GENDIV'
# Arduino-SDI-12_ID1486, Arduino-SDI-12\src\SDI12_boards.cpp:171:9: error: 'REG_GCLK_GENDIV' 
# 
lib_ignore = ${common.cmn_lib_ignore}, SoftwareSerial_ExtInts, AltSoftSerial, MaximDS3231, EnviroDIY_DS3231,  NeoSWSerial, SdFat
  #,SdFat  # need to use - Adafruit Fork\src\SdFatConfig.h

build_src_filter = 
    ${common.cmn_src_filter} 

;https://docs.platformio.org/en/latest/scripting/examples/platformio_ini_custom_options.html
;List as unique path as is needed eg
; \.pio\libdeps\seeed_wio_terminal\EnviroDIY_ModularSensors\src\sensors\MaximDS3231.cpp
; *\src\sensors\MaximDS3231.cpp
custom_build_files_exclude = *\MaximDS3231.cpp *\STSTC3100_Sensor.cpp *\SensirionSHT4x.cpp


#build_flags = -v
# SERIAL2_EN fut:SERIAL2_TE_EN  - only enable when modbusSerial required
# SERIAL3_EN
# SERIAL4_EN fut:SERIAL4_TE_EN  - Tty
build_flags =  ;-v ;review for WIO
    ${common.cmn_build_flags}
    ;-DUSE_RTCLIB=RTC_DS3231 ; or USR_EXTRTCPHY
    ;-UVARIANT_QSPI_BAUD_DEFAULT ;prev def cmd line, also variant.h
    ;-DSDQ_QSPI_FLASH ;HAS W25Q32JVZPIM
    #!more build_flags
    ;Default USB Serial and USE_TINYUSB or specify USE_SERIAL1   
    ;-DUSE_SERIAL1
    ;needed if Seeed WioT which uses Adafruit_TinyUSB_Arduino
    -DUSE_TINYUSB 
    ;-DSTANDARD_SERIAL_OUTPUT=Serial1
    ;-DDEBUGGING_SERIAL_OUTPUT=Serial1
    ;-DDEEP_DEBUGGING_SERIAL_OUTPUT=Serial1
    ;-DCFG_TUSB_DEBUG
    ;-DWIRING_DIGITAL_DEBUG ;still can't connect debug

lib_deps=  ${common.cmn_lib_deps}  ${common.lib_samd_deps} ${common.lib_wio_terminal_deps} ${common.lib_samd51_deps}
extra_scripts = ${common.cmn_arm_extra_scripts} 

    ;OneWire
    ;M5Stack@0.1.9  ;Free_Fonts.h
    ; NTPClient

