; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; python ../build/uf2conv.py -c -b 0x4000 -o oneWireSearch_wio.uf2 .pio/build/seeed_wio_terminal/firmware.bin 
;post:uf2conv.py -c -b 0x4000 -o oneWireSearch_wio.uf2 .pio/build/seeed_wio_terminal/firmware.bin 

[platformio]
description = neilh10/ModularSensors/tools/oneWireSearch
default_envs =seeed_wio_terminal
;default_envs = adafruit_pygamer_m4
;default_envs = adafruit_pygamer_advance_m4
;default_envs = mayfly

;[env:pre_and_post_hooks]
;extra_scripts = post:build_uf2.py

[common]
;cmn_f_cpu=120000000L ;Default
cmn_f_cpu =  48000000L  ;With USB & Also without USBs
cmn_lib_deps =
    OneWwire 
    DallasTemperature
    ;https://github.com/Seeed-Studio/Grove_Temperature_And_Humidity_Sensor

cmn_lib_samd_deps =
https://github.com/adafruit/Adafruit_TinyUSB_Arduino.git#0.8.0 ;Has MIDI after 0.8.0. Requires -DUSE_TINYUSB

cmn_build_flags =
    -Isrc
    ;-DUSE_TINYUSB

cmn_extra_scripts = post:build_uf2.py

[env:seeed_wio_terminal]
platform = atmelsam
board = seeed_wio_terminal
framework = arduino
board_build.f_cpu =  ${common.cmn_f_cpu}
lib_deps = ${common.cmn_lib_deps}  ${common.cmn_lib_samd_deps} 
build_flags =
    ${common.cmn_build_flags}
extra_scripts = ${common.cmn_extra_scripts} 


;https://www.adafruit.com/product/4465
;PyPortal Pynt
;SAMD51J20A 2.4″ diagonal 320 x 240 color

;https://www.adafruit.com/product/4116
;https://learn.adafruit.com/adafruit-pyportal?view=all
;https://docs.platformio.org/en/latest/boards/atmelsam/adafruit_pyportal_m4.html
;SAMD51J20A ~ 3.2″ 320 x 240 color TFT with resistive touch screen
; 4-pin JST I2C connector ight, STEMMA/Grove with pullups to 3.3V. power is 5V
; D3 and D4. These are 3-pin JST digital or analog connectors
;[env:adafruit_pyportal_m4]

;https://docs.platformio.org/en/latest/boards/atmelsam/adafruit_pyportal_m4_titano.html
;SAMD51J20A ~ 3.5″ diagonal 320 x 480
;[env:adafruit_pyportal_m4_titano]
;https://docs.platformio.org/en/latest/boards/atmelsam/adafruit_pyportal_m4_titano.html
;;SAMD51J20A
;[env:adafruit_pyportal_m4_titano]
;https://docs.platformio.org/en/latest/boards/atmelsam/adafruit_pygamer_advance_m4.html
; SAMD51J20A  flash1M ram256K
;[env:adafruit_pygamer_advance_m4]
;https://docs.platformio.org/en/latest/boards/atmelsam/adafruit_pygamer_m4.html
; SAMD51J19A flash512K ram 192K

;Future
[env:adafruit_pygamer_m4]
platform = atmelsam
board = adafruit_pygamer_advance_m4
framework = arduino
board_build.f_cpu =  ${common.cmn_f_cpu}
lib_deps=  ${common.cmn_lib_deps}  ${common.cmn_lib_samd_deps} 
build_flags =
    ${common.cmn_build_flags}
extra_scripts = ${common.cmn_extra_scripts} 

[env:mayfly]
;upload_port = COM11
monitor_speed = 115200
board = mayfly
platform = atmelavr
framework = arduino
lib_deps = ${common.cmn_lib_deps} 
build_flags =
    ${common.cmn_build_flags}
