name: Build Examples

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        example:
          [
            examples/single_sensor/,
            examples/simple_logging/,
            examples/simple_logging_LearnEnviroDIY/,
            examples/DRWI_CitSci/,
            examples/DRWI_LTE/,
            examples/DRWI_NoCellular/,
            examples/double_logger/,
            examples/baro_rho_correction/,
            examples/data_saving/,
            examples/logging_to_MMW/,
            examples/logging_to_ThingSpeak/,
          ]

    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        run: |
          if [[ -z "${GITHUB_HEAD_REF}" ]]; then
            echo "::debug::Push to commit ${GITHUB_SHA}"
            echo "LIBRARY_INSTALL_SOURCE=https://github.com/${GITHUB_REPOSITORY}.git#${GITHUB_SHA}" >> $GITHUB_ENV
          else
            echo "::debug::Pull Request from the ${GITHUB_HEAD_REF} branch"
            echo "LIBRARY_INSTALL_SOURCE=https://github.com/${GITHUB_REPOSITORY}.git#${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          fi

      - name: Restore or Cache pip
        uses: actions/cache@v2.1.5
        with:
          path: ~/.cache/pip
          # if requirements.txt hasn't changed, then it will be a "cache hit" and pip will be restored
          # if requirements.txt HAS changed, it will be a "cache miss" and a new cache of pip will be created if the job completes successfully
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Restore or Cache PlatformIO and Libraries
        uses: actions/cache@v2.1.5
        with:
          path: ~/.platformio
          # if nothing in the lock files has changed, then it will be a "cache hit" and pip will be restored
          # otherwise, it will be a "cache miss" and a new cache of libraries will be created if the job completes successfully
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      # This should be pulled from cache, if there's not a new version
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Run PlatformIO
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
        run: |
          platformio lib --global update
          echo "${{ env.LIBRARY_INSTALL_SOURCE }}"
          platformio ci --project-conf="continuous_integration/platformio.ini"
